/*
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import webdsl.epackage.pkgdsl.ui.internal.PkgdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PkgDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PkgdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PkgdslActivator activator = PkgdslActivator.getInstance();
		return activator != null ? activator.getInjector(PkgdslActivator.WEBDSL_EPACKAGE_PKGDSL_PKGDSL) : null;
	}

}
