/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getPeriodic_constraint <em>Periodic constraint</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getDelay_constraint <em>Delay constraint</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getAge_constraint <em>Age constraint</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getExecution_time_constraint <em>Execution time constraint</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getOrder_constraint <em>Order constraint</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getPattern_constraint <em>Pattern constraint</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getReaction_constraint <em>Reaction constraint</em>}</li>
 * </ul>
 *
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints()
 * @model
 * @generated
 */
public interface Constraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Define</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Define</em>' attribute.
   * @see #setDefine(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Define()
   * @model
   * @generated
   */
  String getDefine();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Constraints#getDefine <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Define</em>' attribute.
   * @see #getDefine()
   * @generated
   */
  void setDefine(String value);

  /**
   * Returns the value of the '<em><b>Periodic constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Periodic_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Periodic constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Periodic_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Periodic_Constraint> getPeriodic_constraint();

  /**
   * Returns the value of the '<em><b>Delay constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Delay_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Delay_Constraint> getDelay_constraint();

  /**
   * Returns the value of the '<em><b>Age constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Age_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Age constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Age_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Age_Constraint> getAge_constraint();

  /**
   * Returns the value of the '<em><b>Execution time constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Execution_Time_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Execution time constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Execution_time_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Execution_Time_Constraint> getExecution_time_constraint();

  /**
   * Returns the value of the '<em><b>Order constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Order_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Order_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Order_Constraint> getOrder_constraint();

  /**
   * Returns the value of the '<em><b>Pattern constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Pattern_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Pattern_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Pattern_Constraint> getPattern_constraint();

  /**
   * Returns the value of the '<em><b>Reaction constraint</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Reaction_Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reaction constraint</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getConstraints_Reaction_constraint()
   * @model containment="true"
   * @generated
   */
  EList<Reaction_Constraint> getReaction_constraint();

} // Constraints
