/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage
 * @generated
 */
public interface PkgDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PkgDslFactory eINSTANCE = webdsl.epackage.pkgdsl.pkgDsl.impl.PkgDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File</em>'.
   * @generated
   */
  File createFile();

  /**
   * Returns a new object of class '<em>EA Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EA Package</em>'.
   * @generated
   */
  EA_Package createEA_Package();

  /**
   * Returns a new object of class '<em>Sub Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Package</em>'.
   * @generated
   */
  Sub_Package createSub_Package();

  /**
   * Returns a new object of class '<em>Nested Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nested Package</em>'.
   * @generated
   */
  Nested_Package createNested_Package();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Elements</em>'.
   * @generated
   */
  Elements createElements();

  /**
   * Returns a new object of class '<em>Timing</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timing</em>'.
   * @generated
   */
  Timing createTiming();

  /**
   * Returns a new object of class '<em>Constraints</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraints</em>'.
   * @generated
   */
  Constraints createConstraints();

  /**
   * Returns a new object of class '<em>Reaction Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reaction Constraint</em>'.
   * @generated
   */
  Reaction_Constraint createReaction_Constraint();

  /**
   * Returns a new object of class '<em>RC Timing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RC Timing Expression</em>'.
   * @generated
   */
  RC_TimingExpression createRC_TimingExpression();

  /**
   * Returns a new object of class '<em>Pattern Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern Constraint</em>'.
   * @generated
   */
  Pattern_Constraint createPattern_Constraint();

  /**
   * Returns a new object of class '<em>Pattern Constraint Timing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern Constraint Timing Expression</em>'.
   * @generated
   */
  Pattern_Constraint_TimingExpression createPattern_Constraint_TimingExpression();

  /**
   * Returns a new object of class '<em>Order Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Order Constraint</em>'.
   * @generated
   */
  Order_Constraint createOrder_Constraint();

  /**
   * Returns a new object of class '<em>Execution Time Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Execution Time Constraint</em>'.
   * @generated
   */
  Execution_Time_Constraint createExecution_Time_Constraint();

  /**
   * Returns a new object of class '<em>ETC Timing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ETC Timing Expression</em>'.
   * @generated
   */
  ETC_TimingExpression createETC_TimingExpression();

  /**
   * Returns a new object of class '<em>Age Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Age Constraint</em>'.
   * @generated
   */
  Age_Constraint createAge_Constraint();

  /**
   * Returns a new object of class '<em>test1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>test1</em>'.
   * @generated
   */
  test1 createtest1();

  /**
   * Returns a new object of class '<em>AC Timing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AC Timing Expression</em>'.
   * @generated
   */
  AC_TimingExpression createAC_TimingExpression();

  /**
   * Returns a new object of class '<em>Delay Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delay Constraint</em>'.
   * @generated
   */
  Delay_Constraint createDelay_Constraint();

  /**
   * Returns a new object of class '<em>DC Timing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DC Timing Expression</em>'.
   * @generated
   */
  DC_TimingExpression createDC_TimingExpression();

  /**
   * Returns a new object of class '<em>Periodic Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Periodic Constraint</em>'.
   * @generated
   */
  Periodic_Constraint createPeriodic_Constraint();

  /**
   * Returns a new object of class '<em>PC Timing Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PC Timing Expression</em>'.
   * @generated
   */
  PC_TimingExpression createPC_TimingExpression();

  /**
   * Returns a new object of class '<em>Descriptions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Descriptions</em>'.
   * @generated
   */
  Descriptions createDescriptions();

  /**
   * Returns a new object of class '<em>Event Chain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Chain</em>'.
   * @generated
   */
  Event_Chain createEvent_Chain();

  /**
   * Returns a new object of class '<em>Event Function Flow Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Function Flow Port</em>'.
   * @generated
   */
  Event_Function_Flow_Port createEvent_Function_Flow_Port();

  /**
   * Returns a new object of class '<em>Event Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Function</em>'.
   * @generated
   */
  Event_Function createEvent_Function();

  /**
   * Returns a new object of class '<em>Unit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unit</em>'.
   * @generated
   */
  Unit createUnit();

  /**
   * Returns a new object of class '<em>Quantity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quantity</em>'.
   * @generated
   */
  Quantity createQuantity();

  /**
   * Returns a new object of class '<em>EA Numerical</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EA Numerical</em>'.
   * @generated
   */
  EA_Numerical createEA_Numerical();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PkgDslPackage getPkgDslPackage();

} //PkgDslFactory
