/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quantity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getUuid <em>Uuid</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getShortname <em>Shortname</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getCategory <em>Category</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getName <em>Name</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getSubstance_exp <em>Substance exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getCurrent_exp <em>Current exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getLength_exp <em>Length exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getIntensity_exp <em>Intensity exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getMass_exp <em>Mass exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getTemp_exp <em>Temp exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getTime_exp <em>Time exp</em>}</li>
 * </ul>
 *
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity()
 * @model
 * @generated
 */
public interface Quantity extends EObject
{
  /**
   * Returns the value of the '<em><b>Define</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Define</em>' attribute.
   * @see #setDefine(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Define()
   * @model
   * @generated
   */
  String getDefine();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getDefine <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Define</em>' attribute.
   * @see #getDefine()
   * @generated
   */
  void setDefine(String value);

  /**
   * Returns the value of the '<em><b>Uuid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uuid</em>' attribute.
   * @see #setUuid(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Uuid()
   * @model
   * @generated
   */
  String getUuid();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getUuid <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uuid</em>' attribute.
   * @see #getUuid()
   * @generated
   */
  void setUuid(String value);

  /**
   * Returns the value of the '<em><b>Shortname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shortname</em>' attribute.
   * @see #setShortname(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Shortname()
   * @model
   * @generated
   */
  String getShortname();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getShortname <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shortname</em>' attribute.
   * @see #getShortname()
   * @generated
   */
  void setShortname(String value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' attribute.
   * @see #setCategory(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Category()
   * @model
   * @generated
   */
  String getCategory();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getCategory <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' attribute.
   * @see #getCategory()
   * @generated
   */
  void setCategory(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Substance exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substance exp</em>' attribute.
   * @see #setSubstance_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Substance_exp()
   * @model
   * @generated
   */
  int getSubstance_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getSubstance_exp <em>Substance exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Substance exp</em>' attribute.
   * @see #getSubstance_exp()
   * @generated
   */
  void setSubstance_exp(int value);

  /**
   * Returns the value of the '<em><b>Current exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current exp</em>' attribute.
   * @see #setCurrent_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Current_exp()
   * @model
   * @generated
   */
  int getCurrent_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getCurrent_exp <em>Current exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current exp</em>' attribute.
   * @see #getCurrent_exp()
   * @generated
   */
  void setCurrent_exp(int value);

  /**
   * Returns the value of the '<em><b>Length exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length exp</em>' attribute.
   * @see #setLength_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Length_exp()
   * @model
   * @generated
   */
  int getLength_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getLength_exp <em>Length exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length exp</em>' attribute.
   * @see #getLength_exp()
   * @generated
   */
  void setLength_exp(int value);

  /**
   * Returns the value of the '<em><b>Intensity exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intensity exp</em>' attribute.
   * @see #setIntensity_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Intensity_exp()
   * @model
   * @generated
   */
  int getIntensity_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getIntensity_exp <em>Intensity exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intensity exp</em>' attribute.
   * @see #getIntensity_exp()
   * @generated
   */
  void setIntensity_exp(int value);

  /**
   * Returns the value of the '<em><b>Mass exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mass exp</em>' attribute.
   * @see #setMass_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Mass_exp()
   * @model
   * @generated
   */
  int getMass_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getMass_exp <em>Mass exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mass exp</em>' attribute.
   * @see #getMass_exp()
   * @generated
   */
  void setMass_exp(int value);

  /**
   * Returns the value of the '<em><b>Temp exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp exp</em>' attribute.
   * @see #setTemp_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Temp_exp()
   * @model
   * @generated
   */
  int getTemp_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getTemp_exp <em>Temp exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temp exp</em>' attribute.
   * @see #getTemp_exp()
   * @generated
   */
  void setTemp_exp(int value);

  /**
   * Returns the value of the '<em><b>Time exp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time exp</em>' attribute.
   * @see #setTime_exp(int)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getQuantity_Time_exp()
   * @model
   * @generated
   */
  int getTime_exp();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Quantity#getTime_exp <em>Time exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time exp</em>' attribute.
   * @see #getTime_exp()
   * @generated
   */
  void setTime_exp(int value);

} // Quantity
