/*
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class PkgDslWebModule extends AbstractPkgDslWebModule {
}
