/*
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import webdsl.epackage.pkgdsl.PkgDslRuntimeModule;
import webdsl.epackage.pkgdsl.PkgDslStandaloneSetup;
import webdsl.epackage.pkgdsl.ide.PkgDslIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class PkgDslWebSetup extends PkgDslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PkgDslRuntimeModule(), new PkgDslIdeModule(), new PkgDslWebModule()));
	}
	
}
