/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import webdsl.epackage.pkgdsl.pkgDsl.EA_Numerical;
import webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EA Numerical</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getUuid <em>Uuid</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getShortname <em>Shortname</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getCategory <em>Category</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getName <em>Name</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getText <em>Text</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getMax <em>Max</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getMin <em>Min</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.EA_NumericalImpl#getData_unit <em>Data unit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EA_NumericalImpl extends MinimalEObjectImpl.Container implements EA_Numerical
{
  /**
   * The default value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected static final String DEFINE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected String define = DEFINE_EDEFAULT;

  /**
   * The default value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected static final String UUID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected String uuid = UUID_EDEFAULT;

  /**
   * The default value of the '{@link #getShortname() <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortname()
   * @generated
   * @ordered
   */
  protected static final String SHORTNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShortname() <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortname()
   * @generated
   * @ordered
   */
  protected String shortname = SHORTNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected static final String CATEGORY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected String category = CATEGORY_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected static final String TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected String text = TEXT_EDEFAULT;

  /**
   * The default value of the '{@link #getMax() <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax()
   * @generated
   * @ordered
   */
  protected static final String MAX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMax() <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMax()
   * @generated
   * @ordered
   */
  protected String max = MAX_EDEFAULT;

  /**
   * The default value of the '{@link #getMin() <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin()
   * @generated
   * @ordered
   */
  protected static final String MIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMin() <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMin()
   * @generated
   * @ordered
   */
  protected String min = MIN_EDEFAULT;

  /**
   * The default value of the '{@link #getData_unit() <em>Data unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getData_unit()
   * @generated
   * @ordered
   */
  protected static final String DATA_UNIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getData_unit() <em>Data unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getData_unit()
   * @generated
   * @ordered
   */
  protected String data_unit = DATA_UNIT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EA_NumericalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PkgDslPackage.Literals.EA_NUMERICAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefine()
  {
    return define;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefine(String newDefine)
  {
    String oldDefine = define;
    define = newDefine;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__DEFINE, oldDefine, define));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUuid()
  {
    return uuid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUuid(String newUuid)
  {
    String oldUuid = uuid;
    uuid = newUuid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__UUID, oldUuid, uuid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getShortname()
  {
    return shortname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShortname(String newShortname)
  {
    String oldShortname = shortname;
    shortname = newShortname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__SHORTNAME, oldShortname, shortname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCategory()
  {
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCategory(String newCategory)
  {
    String oldCategory = category;
    category = newCategory;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__CATEGORY, oldCategory, category));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getText()
  {
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setText(String newText)
  {
    String oldText = text;
    text = newText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__TEXT, oldText, text));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMax()
  {
    return max;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMax(String newMax)
  {
    String oldMax = max;
    max = newMax;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__MAX, oldMax, max));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMin()
  {
    return min;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMin(String newMin)
  {
    String oldMin = min;
    min = newMin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__MIN, oldMin, min));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getData_unit()
  {
    return data_unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setData_unit(String newData_unit)
  {
    String oldData_unit = data_unit;
    data_unit = newData_unit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EA_NUMERICAL__DATA_UNIT, oldData_unit, data_unit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PkgDslPackage.EA_NUMERICAL__DEFINE:
        return getDefine();
      case PkgDslPackage.EA_NUMERICAL__UUID:
        return getUuid();
      case PkgDslPackage.EA_NUMERICAL__SHORTNAME:
        return getShortname();
      case PkgDslPackage.EA_NUMERICAL__CATEGORY:
        return getCategory();
      case PkgDslPackage.EA_NUMERICAL__NAME:
        return getName();
      case PkgDslPackage.EA_NUMERICAL__TEXT:
        return getText();
      case PkgDslPackage.EA_NUMERICAL__MAX:
        return getMax();
      case PkgDslPackage.EA_NUMERICAL__MIN:
        return getMin();
      case PkgDslPackage.EA_NUMERICAL__DATA_UNIT:
        return getData_unit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PkgDslPackage.EA_NUMERICAL__DEFINE:
        setDefine((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__UUID:
        setUuid((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__SHORTNAME:
        setShortname((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__CATEGORY:
        setCategory((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__NAME:
        setName((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__TEXT:
        setText((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__MAX:
        setMax((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__MIN:
        setMin((String)newValue);
        return;
      case PkgDslPackage.EA_NUMERICAL__DATA_UNIT:
        setData_unit((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.EA_NUMERICAL__DEFINE:
        setDefine(DEFINE_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__UUID:
        setUuid(UUID_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__SHORTNAME:
        setShortname(SHORTNAME_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__CATEGORY:
        setCategory(CATEGORY_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__TEXT:
        setText(TEXT_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__MAX:
        setMax(MAX_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__MIN:
        setMin(MIN_EDEFAULT);
        return;
      case PkgDslPackage.EA_NUMERICAL__DATA_UNIT:
        setData_unit(DATA_UNIT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.EA_NUMERICAL__DEFINE:
        return DEFINE_EDEFAULT == null ? define != null : !DEFINE_EDEFAULT.equals(define);
      case PkgDslPackage.EA_NUMERICAL__UUID:
        return UUID_EDEFAULT == null ? uuid != null : !UUID_EDEFAULT.equals(uuid);
      case PkgDslPackage.EA_NUMERICAL__SHORTNAME:
        return SHORTNAME_EDEFAULT == null ? shortname != null : !SHORTNAME_EDEFAULT.equals(shortname);
      case PkgDslPackage.EA_NUMERICAL__CATEGORY:
        return CATEGORY_EDEFAULT == null ? category != null : !CATEGORY_EDEFAULT.equals(category);
      case PkgDslPackage.EA_NUMERICAL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PkgDslPackage.EA_NUMERICAL__TEXT:
        return TEXT_EDEFAULT == null ? text != null : !TEXT_EDEFAULT.equals(text);
      case PkgDslPackage.EA_NUMERICAL__MAX:
        return MAX_EDEFAULT == null ? max != null : !MAX_EDEFAULT.equals(max);
      case PkgDslPackage.EA_NUMERICAL__MIN:
        return MIN_EDEFAULT == null ? min != null : !MIN_EDEFAULT.equals(min);
      case PkgDslPackage.EA_NUMERICAL__DATA_UNIT:
        return DATA_UNIT_EDEFAULT == null ? data_unit != null : !DATA_UNIT_EDEFAULT.equals(data_unit);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (define: ");
    result.append(define);
    result.append(", uuid: ");
    result.append(uuid);
    result.append(", shortname: ");
    result.append(shortname);
    result.append(", category: ");
    result.append(category);
    result.append(", name: ");
    result.append(name);
    result.append(", text: ");
    result.append(text);
    result.append(", max: ");
    result.append(max);
    result.append(", min: ");
    result.append(min);
    result.append(", data_unit: ");
    result.append(data_unit);
    result.append(')');
    return result.toString();
  }

} //EA_NumericalImpl
