/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port;
import webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event Function Flow Port</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getUuid <em>Uuid</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getShortname <em>Shortname</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getCategory <em>Category</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getName <em>Name</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getFunc_type <em>Func type</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getFunc_value <em>Func value</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getFunc_prototype <em>Func prototype</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.Event_Function_Flow_PortImpl#getFunc_flow_port <em>Func flow port</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Event_Function_Flow_PortImpl extends MinimalEObjectImpl.Container implements Event_Function_Flow_Port
{
  /**
   * The default value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected static final String DEFINE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected String define = DEFINE_EDEFAULT;

  /**
   * The default value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected static final String UUID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected String uuid = UUID_EDEFAULT;

  /**
   * The default value of the '{@link #getShortname() <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortname()
   * @generated
   * @ordered
   */
  protected static final String SHORTNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShortname() <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortname()
   * @generated
   * @ordered
   */
  protected String shortname = SHORTNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected static final String CATEGORY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected String category = CATEGORY_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getFunc_type() <em>Func type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_type()
   * @generated
   * @ordered
   */
  protected static final String FUNC_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFunc_type() <em>Func type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_type()
   * @generated
   * @ordered
   */
  protected String func_type = FUNC_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getFunc_value() <em>Func value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_value()
   * @generated
   * @ordered
   */
  protected static final String FUNC_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFunc_value() <em>Func value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_value()
   * @generated
   * @ordered
   */
  protected String func_value = FUNC_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getFunc_prototype() <em>Func prototype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_prototype()
   * @generated
   * @ordered
   */
  protected static final String FUNC_PROTOTYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFunc_prototype() <em>Func prototype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_prototype()
   * @generated
   * @ordered
   */
  protected String func_prototype = FUNC_PROTOTYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getFunc_flow_port() <em>Func flow port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_flow_port()
   * @generated
   * @ordered
   */
  protected static final String FUNC_FLOW_PORT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFunc_flow_port() <em>Func flow port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunc_flow_port()
   * @generated
   * @ordered
   */
  protected String func_flow_port = FUNC_FLOW_PORT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Event_Function_Flow_PortImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PkgDslPackage.Literals.EVENT_FUNCTION_FLOW_PORT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefine()
  {
    return define;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefine(String newDefine)
  {
    String oldDefine = define;
    define = newDefine;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__DEFINE, oldDefine, define));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUuid()
  {
    return uuid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUuid(String newUuid)
  {
    String oldUuid = uuid;
    uuid = newUuid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__UUID, oldUuid, uuid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getShortname()
  {
    return shortname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShortname(String newShortname)
  {
    String oldShortname = shortname;
    shortname = newShortname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__SHORTNAME, oldShortname, shortname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCategory()
  {
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCategory(String newCategory)
  {
    String oldCategory = category;
    category = newCategory;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__CATEGORY, oldCategory, category));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFunc_type()
  {
    return func_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunc_type(String newFunc_type)
  {
    String oldFunc_type = func_type;
    func_type = newFunc_type;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_TYPE, oldFunc_type, func_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFunc_value()
  {
    return func_value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunc_value(String newFunc_value)
  {
    String oldFunc_value = func_value;
    func_value = newFunc_value;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_VALUE, oldFunc_value, func_value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFunc_prototype()
  {
    return func_prototype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunc_prototype(String newFunc_prototype)
  {
    String oldFunc_prototype = func_prototype;
    func_prototype = newFunc_prototype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_PROTOTYPE, oldFunc_prototype, func_prototype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFunc_flow_port()
  {
    return func_flow_port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunc_flow_port(String newFunc_flow_port)
  {
    String oldFunc_flow_port = func_flow_port;
    func_flow_port = newFunc_flow_port;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_FLOW_PORT, oldFunc_flow_port, func_flow_port));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__DEFINE:
        return getDefine();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__UUID:
        return getUuid();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__SHORTNAME:
        return getShortname();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__CATEGORY:
        return getCategory();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__NAME:
        return getName();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_TYPE:
        return getFunc_type();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_VALUE:
        return getFunc_value();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_PROTOTYPE:
        return getFunc_prototype();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_FLOW_PORT:
        return getFunc_flow_port();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__DEFINE:
        setDefine((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__UUID:
        setUuid((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__SHORTNAME:
        setShortname((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__CATEGORY:
        setCategory((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__NAME:
        setName((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_TYPE:
        setFunc_type((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_VALUE:
        setFunc_value((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_PROTOTYPE:
        setFunc_prototype((String)newValue);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_FLOW_PORT:
        setFunc_flow_port((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__DEFINE:
        setDefine(DEFINE_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__UUID:
        setUuid(UUID_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__SHORTNAME:
        setShortname(SHORTNAME_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__CATEGORY:
        setCategory(CATEGORY_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_TYPE:
        setFunc_type(FUNC_TYPE_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_VALUE:
        setFunc_value(FUNC_VALUE_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_PROTOTYPE:
        setFunc_prototype(FUNC_PROTOTYPE_EDEFAULT);
        return;
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_FLOW_PORT:
        setFunc_flow_port(FUNC_FLOW_PORT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__DEFINE:
        return DEFINE_EDEFAULT == null ? define != null : !DEFINE_EDEFAULT.equals(define);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__UUID:
        return UUID_EDEFAULT == null ? uuid != null : !UUID_EDEFAULT.equals(uuid);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__SHORTNAME:
        return SHORTNAME_EDEFAULT == null ? shortname != null : !SHORTNAME_EDEFAULT.equals(shortname);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__CATEGORY:
        return CATEGORY_EDEFAULT == null ? category != null : !CATEGORY_EDEFAULT.equals(category);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_TYPE:
        return FUNC_TYPE_EDEFAULT == null ? func_type != null : !FUNC_TYPE_EDEFAULT.equals(func_type);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_VALUE:
        return FUNC_VALUE_EDEFAULT == null ? func_value != null : !FUNC_VALUE_EDEFAULT.equals(func_value);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_PROTOTYPE:
        return FUNC_PROTOTYPE_EDEFAULT == null ? func_prototype != null : !FUNC_PROTOTYPE_EDEFAULT.equals(func_prototype);
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT__FUNC_FLOW_PORT:
        return FUNC_FLOW_PORT_EDEFAULT == null ? func_flow_port != null : !FUNC_FLOW_PORT_EDEFAULT.equals(func_flow_port);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (define: ");
    result.append(define);
    result.append(", uuid: ");
    result.append(uuid);
    result.append(", shortname: ");
    result.append(shortname);
    result.append(", category: ");
    result.append(category);
    result.append(", name: ");
    result.append(name);
    result.append(", func_type: ");
    result.append(func_type);
    result.append(", func_value: ");
    result.append(func_value);
    result.append(", func_prototype: ");
    result.append(func_prototype);
    result.append(", func_flow_port: ");
    result.append(func_flow_port);
    result.append(')');
    return result.toString();
  }

} //Event_Function_Flow_PortImpl
