/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Age Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Age_Constraint#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Age_Constraint#getTest <em>Test</em>}</li>
 * </ul>
 *
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getAge_Constraint()
 * @model
 * @generated
 */
public interface Age_Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Define</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Define</em>' attribute.
   * @see #setDefine(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getAge_Constraint_Define()
   * @model
   * @generated
   */
  String getDefine();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Age_Constraint#getDefine <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Define</em>' attribute.
   * @see #getDefine()
   * @generated
   */
  void setDefine(String value);

  /**
   * Returns the value of the '<em><b>Test</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test</em>' containment reference.
   * @see #setTest(test1)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getAge_Constraint_Test()
   * @model containment="true"
   * @generated
   */
  test1 getTest();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Age_Constraint#getTest <em>Test</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test</em>' containment reference.
   * @see #getTest()
   * @generated
   */
  void setTest(test1 value);

} // Age_Constraint
