/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delay Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getUuid <em>Uuid</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getShortname <em>Shortname</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getCategory <em>Category</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getName <em>Name</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getTarget <em>Target</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getSource <em>Source</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getTimingexpression <em>Timingexpression</em>}</li>
 * </ul>
 *
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint()
 * @model
 * @generated
 */
public interface Delay_Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Define</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Define</em>' attribute.
   * @see #setDefine(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Define()
   * @model
   * @generated
   */
  String getDefine();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getDefine <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Define</em>' attribute.
   * @see #getDefine()
   * @generated
   */
  void setDefine(String value);

  /**
   * Returns the value of the '<em><b>Uuid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uuid</em>' attribute.
   * @see #setUuid(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Uuid()
   * @model
   * @generated
   */
  String getUuid();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getUuid <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uuid</em>' attribute.
   * @see #getUuid()
   * @generated
   */
  void setUuid(String value);

  /**
   * Returns the value of the '<em><b>Shortname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shortname</em>' attribute.
   * @see #setShortname(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Shortname()
   * @model
   * @generated
   */
  String getShortname();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getShortname <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shortname</em>' attribute.
   * @see #getShortname()
   * @generated
   */
  void setShortname(String value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' attribute.
   * @see #setCategory(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Category()
   * @model
   * @generated
   */
  String getCategory();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getCategory <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' attribute.
   * @see #getCategory()
   * @generated
   */
  void setCategory(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Delay_Constraint#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Timingexpression</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.DC_TimingExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timingexpression</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getDelay_Constraint_Timingexpression()
   * @model containment="true"
   * @generated
   */
  EList<DC_TimingExpression> getTimingexpression();

} // Delay_Constraint
