/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Function Flow Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getUuid <em>Uuid</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getShortname <em>Shortname</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getCategory <em>Category</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getName <em>Name</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_type <em>Func type</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_value <em>Func value</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_prototype <em>Func prototype</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_flow_port <em>Func flow port</em>}</li>
 * </ul>
 *
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port()
 * @model
 * @generated
 */
public interface Event_Function_Flow_Port extends EObject
{
  /**
   * Returns the value of the '<em><b>Define</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Define</em>' attribute.
   * @see #setDefine(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Define()
   * @model
   * @generated
   */
  String getDefine();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getDefine <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Define</em>' attribute.
   * @see #getDefine()
   * @generated
   */
  void setDefine(String value);

  /**
   * Returns the value of the '<em><b>Uuid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uuid</em>' attribute.
   * @see #setUuid(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Uuid()
   * @model
   * @generated
   */
  String getUuid();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getUuid <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uuid</em>' attribute.
   * @see #getUuid()
   * @generated
   */
  void setUuid(String value);

  /**
   * Returns the value of the '<em><b>Shortname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shortname</em>' attribute.
   * @see #setShortname(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Shortname()
   * @model
   * @generated
   */
  String getShortname();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getShortname <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shortname</em>' attribute.
   * @see #getShortname()
   * @generated
   */
  void setShortname(String value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' attribute.
   * @see #setCategory(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Category()
   * @model
   * @generated
   */
  String getCategory();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getCategory <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' attribute.
   * @see #getCategory()
   * @generated
   */
  void setCategory(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Func type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func type</em>' attribute.
   * @see #setFunc_type(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Func_type()
   * @model
   * @generated
   */
  String getFunc_type();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_type <em>Func type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func type</em>' attribute.
   * @see #getFunc_type()
   * @generated
   */
  void setFunc_type(String value);

  /**
   * Returns the value of the '<em><b>Func value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func value</em>' attribute.
   * @see #setFunc_value(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Func_value()
   * @model
   * @generated
   */
  String getFunc_value();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_value <em>Func value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func value</em>' attribute.
   * @see #getFunc_value()
   * @generated
   */
  void setFunc_value(String value);

  /**
   * Returns the value of the '<em><b>Func prototype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func prototype</em>' attribute.
   * @see #setFunc_prototype(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Func_prototype()
   * @model
   * @generated
   */
  String getFunc_prototype();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_prototype <em>Func prototype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func prototype</em>' attribute.
   * @see #getFunc_prototype()
   * @generated
   */
  void setFunc_prototype(String value);

  /**
   * Returns the value of the '<em><b>Func flow port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func flow port</em>' attribute.
   * @see #setFunc_flow_port(String)
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getEvent_Function_Flow_Port_Func_flow_port()
   * @model
   * @generated
   */
  String getFunc_flow_port();

  /**
   * Sets the value of the '{@link webdsl.epackage.pkgdsl.pkgDsl.Event_Function_Flow_Port#getFunc_flow_port <em>Func flow port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func flow port</em>' attribute.
   * @see #getFunc_flow_port()
   * @generated
   */
  void setFunc_flow_port(String value);

} // Event_Function_Flow_Port
