/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.File#getEa_package <em>Ea package</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.File#getTiming <em>Timing</em>}</li>
 * </ul>
 *
 * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getFile()
 * @model
 * @generated
 */
public interface File extends EObject
{
  /**
   * Returns the value of the '<em><b>Ea package</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.EA_Package}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ea package</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getFile_Ea_package()
   * @model containment="true"
   * @generated
   */
  EList<EA_Package> getEa_package();

  /**
   * Returns the value of the '<em><b>Timing</b></em>' containment reference list.
   * The list contents are of type {@link webdsl.epackage.pkgdsl.pkgDsl.Timing}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timing</em>' containment reference list.
   * @see webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage#getFile_Timing()
   * @model containment="true"
   * @generated
   */
  EList<Timing> getTiming();

} // File
