/*
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import webdsl.epackage.pkgdsl.ide.contentassist.PkgDslWebContentProposalProvider;

/**
 * Use this class to register ide components.
 */
public class PkgDslIdeModule extends AbstractPkgDslIdeModule {
	
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
	    return PkgDslWebContentProposalProvider.class;
	}
}
