/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import webdsl.epackage.pkgdsl.pkgDsl.EA_Numerical;
import webdsl.epackage.pkgdsl.pkgDsl.Elements;
import webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage;
import webdsl.epackage.pkgdsl.pkgDsl.Quantity;
import webdsl.epackage.pkgdsl.pkgDsl.Timing;
import webdsl.epackage.pkgdsl.pkgDsl.Unit;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Elements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.ElementsImpl#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.ElementsImpl#getEa_numerical <em>Ea numerical</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.ElementsImpl#getUnit <em>Unit</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.ElementsImpl#getQunatity <em>Qunatity</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.ElementsImpl#getTiming <em>Timing</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ElementsImpl extends MinimalEObjectImpl.Container implements Elements
{
  /**
   * The default value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected static final String DEFINE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected String define = DEFINE_EDEFAULT;

  /**
   * The cached value of the '{@link #getEa_numerical() <em>Ea numerical</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEa_numerical()
   * @generated
   * @ordered
   */
  protected EList<EA_Numerical> ea_numerical;

  /**
   * The cached value of the '{@link #getUnit() <em>Unit</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnit()
   * @generated
   * @ordered
   */
  protected EList<Unit> unit;

  /**
   * The cached value of the '{@link #getQunatity() <em>Qunatity</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQunatity()
   * @generated
   * @ordered
   */
  protected EList<Quantity> qunatity;

  /**
   * The cached value of the '{@link #getTiming() <em>Timing</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTiming()
   * @generated
   * @ordered
   */
  protected EList<Timing> timing;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PkgDslPackage.Literals.ELEMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefine()
  {
    return define;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefine(String newDefine)
  {
    String oldDefine = define;
    define = newDefine;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.ELEMENTS__DEFINE, oldDefine, define));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EA_Numerical> getEa_numerical()
  {
    if (ea_numerical == null)
    {
      ea_numerical = new EObjectContainmentEList<EA_Numerical>(EA_Numerical.class, this, PkgDslPackage.ELEMENTS__EA_NUMERICAL);
    }
    return ea_numerical;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Unit> getUnit()
  {
    if (unit == null)
    {
      unit = new EObjectContainmentEList<Unit>(Unit.class, this, PkgDslPackage.ELEMENTS__UNIT);
    }
    return unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Quantity> getQunatity()
  {
    if (qunatity == null)
    {
      qunatity = new EObjectContainmentEList<Quantity>(Quantity.class, this, PkgDslPackage.ELEMENTS__QUNATITY);
    }
    return qunatity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Timing> getTiming()
  {
    if (timing == null)
    {
      timing = new EObjectContainmentEList<Timing>(Timing.class, this, PkgDslPackage.ELEMENTS__TIMING);
    }
    return timing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PkgDslPackage.ELEMENTS__EA_NUMERICAL:
        return ((InternalEList<?>)getEa_numerical()).basicRemove(otherEnd, msgs);
      case PkgDslPackage.ELEMENTS__UNIT:
        return ((InternalEList<?>)getUnit()).basicRemove(otherEnd, msgs);
      case PkgDslPackage.ELEMENTS__QUNATITY:
        return ((InternalEList<?>)getQunatity()).basicRemove(otherEnd, msgs);
      case PkgDslPackage.ELEMENTS__TIMING:
        return ((InternalEList<?>)getTiming()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PkgDslPackage.ELEMENTS__DEFINE:
        return getDefine();
      case PkgDslPackage.ELEMENTS__EA_NUMERICAL:
        return getEa_numerical();
      case PkgDslPackage.ELEMENTS__UNIT:
        return getUnit();
      case PkgDslPackage.ELEMENTS__QUNATITY:
        return getQunatity();
      case PkgDslPackage.ELEMENTS__TIMING:
        return getTiming();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PkgDslPackage.ELEMENTS__DEFINE:
        setDefine((String)newValue);
        return;
      case PkgDslPackage.ELEMENTS__EA_NUMERICAL:
        getEa_numerical().clear();
        getEa_numerical().addAll((Collection<? extends EA_Numerical>)newValue);
        return;
      case PkgDslPackage.ELEMENTS__UNIT:
        getUnit().clear();
        getUnit().addAll((Collection<? extends Unit>)newValue);
        return;
      case PkgDslPackage.ELEMENTS__QUNATITY:
        getQunatity().clear();
        getQunatity().addAll((Collection<? extends Quantity>)newValue);
        return;
      case PkgDslPackage.ELEMENTS__TIMING:
        getTiming().clear();
        getTiming().addAll((Collection<? extends Timing>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.ELEMENTS__DEFINE:
        setDefine(DEFINE_EDEFAULT);
        return;
      case PkgDslPackage.ELEMENTS__EA_NUMERICAL:
        getEa_numerical().clear();
        return;
      case PkgDslPackage.ELEMENTS__UNIT:
        getUnit().clear();
        return;
      case PkgDslPackage.ELEMENTS__QUNATITY:
        getQunatity().clear();
        return;
      case PkgDslPackage.ELEMENTS__TIMING:
        getTiming().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.ELEMENTS__DEFINE:
        return DEFINE_EDEFAULT == null ? define != null : !DEFINE_EDEFAULT.equals(define);
      case PkgDslPackage.ELEMENTS__EA_NUMERICAL:
        return ea_numerical != null && !ea_numerical.isEmpty();
      case PkgDslPackage.ELEMENTS__UNIT:
        return unit != null && !unit.isEmpty();
      case PkgDslPackage.ELEMENTS__QUNATITY:
        return qunatity != null && !qunatity.isEmpty();
      case PkgDslPackage.ELEMENTS__TIMING:
        return timing != null && !timing.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (define: ");
    result.append(define);
    result.append(')');
    return result.toString();
  }

} //ElementsImpl
