/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import webdsl.epackage.pkgdsl.pkgDsl.EA_Package;
import webdsl.epackage.pkgdsl.pkgDsl.File;
import webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage;
import webdsl.epackage.pkgdsl.pkgDsl.Timing;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.FileImpl#getEa_package <em>Ea package</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.FileImpl#getTiming <em>Timing</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FileImpl extends MinimalEObjectImpl.Container implements File
{
  /**
   * The cached value of the '{@link #getEa_package() <em>Ea package</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEa_package()
   * @generated
   * @ordered
   */
  protected EList<EA_Package> ea_package;

  /**
   * The cached value of the '{@link #getTiming() <em>Timing</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTiming()
   * @generated
   * @ordered
   */
  protected EList<Timing> timing;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PkgDslPackage.Literals.FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EA_Package> getEa_package()
  {
    if (ea_package == null)
    {
      ea_package = new EObjectContainmentEList<EA_Package>(EA_Package.class, this, PkgDslPackage.FILE__EA_PACKAGE);
    }
    return ea_package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Timing> getTiming()
  {
    if (timing == null)
    {
      timing = new EObjectContainmentEList<Timing>(Timing.class, this, PkgDslPackage.FILE__TIMING);
    }
    return timing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PkgDslPackage.FILE__EA_PACKAGE:
        return ((InternalEList<?>)getEa_package()).basicRemove(otherEnd, msgs);
      case PkgDslPackage.FILE__TIMING:
        return ((InternalEList<?>)getTiming()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PkgDslPackage.FILE__EA_PACKAGE:
        return getEa_package();
      case PkgDslPackage.FILE__TIMING:
        return getTiming();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PkgDslPackage.FILE__EA_PACKAGE:
        getEa_package().clear();
        getEa_package().addAll((Collection<? extends EA_Package>)newValue);
        return;
      case PkgDslPackage.FILE__TIMING:
        getTiming().clear();
        getTiming().addAll((Collection<? extends Timing>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.FILE__EA_PACKAGE:
        getEa_package().clear();
        return;
      case PkgDslPackage.FILE__TIMING:
        getTiming().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.FILE__EA_PACKAGE:
        return ea_package != null && !ea_package.isEmpty();
      case PkgDslPackage.FILE__TIMING:
        return timing != null && !timing.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FileImpl
