/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import webdsl.epackage.pkgdsl.pkgDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PkgDslFactoryImpl extends EFactoryImpl implements PkgDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PkgDslFactory init()
  {
    try
    {
      PkgDslFactory thePkgDslFactory = (PkgDslFactory)EPackage.Registry.INSTANCE.getEFactory(PkgDslPackage.eNS_URI);
      if (thePkgDslFactory != null)
      {
        return thePkgDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PkgDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PkgDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PkgDslPackage.FILE: return createFile();
      case PkgDslPackage.EA_PACKAGE: return createEA_Package();
      case PkgDslPackage.SUB_PACKAGE: return createSub_Package();
      case PkgDslPackage.NESTED_PACKAGE: return createNested_Package();
      case PkgDslPackage.ELEMENT: return createElement();
      case PkgDslPackage.ELEMENTS: return createElements();
      case PkgDslPackage.TIMING: return createTiming();
      case PkgDslPackage.CONSTRAINTS: return createConstraints();
      case PkgDslPackage.REACTION_CONSTRAINT: return createReaction_Constraint();
      case PkgDslPackage.RC_TIMING_EXPRESSION: return createRC_TimingExpression();
      case PkgDslPackage.PATTERN_CONSTRAINT: return createPattern_Constraint();
      case PkgDslPackage.PATTERN_CONSTRAINT_TIMING_EXPRESSION: return createPattern_Constraint_TimingExpression();
      case PkgDslPackage.ORDER_CONSTRAINT: return createOrder_Constraint();
      case PkgDslPackage.EXECUTION_TIME_CONSTRAINT: return createExecution_Time_Constraint();
      case PkgDslPackage.ETC_TIMING_EXPRESSION: return createETC_TimingExpression();
      case PkgDslPackage.AGE_CONSTRAINT: return createAge_Constraint();
      case PkgDslPackage.TEST1: return createtest1();
      case PkgDslPackage.AC_TIMING_EXPRESSION: return createAC_TimingExpression();
      case PkgDslPackage.DELAY_CONSTRAINT: return createDelay_Constraint();
      case PkgDslPackage.DC_TIMING_EXPRESSION: return createDC_TimingExpression();
      case PkgDslPackage.PERIODIC_CONSTRAINT: return createPeriodic_Constraint();
      case PkgDslPackage.PC_TIMING_EXPRESSION: return createPC_TimingExpression();
      case PkgDslPackage.DESCRIPTIONS: return createDescriptions();
      case PkgDslPackage.EVENT_CHAIN: return createEvent_Chain();
      case PkgDslPackage.EVENT_FUNCTION_FLOW_PORT: return createEvent_Function_Flow_Port();
      case PkgDslPackage.EVENT_FUNCTION: return createEvent_Function();
      case PkgDslPackage.UNIT: return createUnit();
      case PkgDslPackage.QUANTITY: return createQuantity();
      case PkgDslPackage.EA_NUMERICAL: return createEA_Numerical();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public File createFile()
  {
    FileImpl file = new FileImpl();
    return file;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EA_Package createEA_Package()
  {
    EA_PackageImpl eA_Package = new EA_PackageImpl();
    return eA_Package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sub_Package createSub_Package()
  {
    Sub_PackageImpl sub_Package = new Sub_PackageImpl();
    return sub_Package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nested_Package createNested_Package()
  {
    Nested_PackageImpl nested_Package = new Nested_PackageImpl();
    return nested_Package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element createElement()
  {
    ElementImpl element = new ElementImpl();
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Elements createElements()
  {
    ElementsImpl elements = new ElementsImpl();
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Timing createTiming()
  {
    TimingImpl timing = new TimingImpl();
    return timing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Constraints createConstraints()
  {
    ConstraintsImpl constraints = new ConstraintsImpl();
    return constraints;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reaction_Constraint createReaction_Constraint()
  {
    Reaction_ConstraintImpl reaction_Constraint = new Reaction_ConstraintImpl();
    return reaction_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RC_TimingExpression createRC_TimingExpression()
  {
    RC_TimingExpressionImpl rC_TimingExpression = new RC_TimingExpressionImpl();
    return rC_TimingExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pattern_Constraint createPattern_Constraint()
  {
    Pattern_ConstraintImpl pattern_Constraint = new Pattern_ConstraintImpl();
    return pattern_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pattern_Constraint_TimingExpression createPattern_Constraint_TimingExpression()
  {
    Pattern_Constraint_TimingExpressionImpl pattern_Constraint_TimingExpression = new Pattern_Constraint_TimingExpressionImpl();
    return pattern_Constraint_TimingExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Order_Constraint createOrder_Constraint()
  {
    Order_ConstraintImpl order_Constraint = new Order_ConstraintImpl();
    return order_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Execution_Time_Constraint createExecution_Time_Constraint()
  {
    Execution_Time_ConstraintImpl execution_Time_Constraint = new Execution_Time_ConstraintImpl();
    return execution_Time_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ETC_TimingExpression createETC_TimingExpression()
  {
    ETC_TimingExpressionImpl etC_TimingExpression = new ETC_TimingExpressionImpl();
    return etC_TimingExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Age_Constraint createAge_Constraint()
  {
    Age_ConstraintImpl age_Constraint = new Age_ConstraintImpl();
    return age_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public test1 createtest1()
  {
    test1Impl test1 = new test1Impl();
    return test1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AC_TimingExpression createAC_TimingExpression()
  {
    AC_TimingExpressionImpl aC_TimingExpression = new AC_TimingExpressionImpl();
    return aC_TimingExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Delay_Constraint createDelay_Constraint()
  {
    Delay_ConstraintImpl delay_Constraint = new Delay_ConstraintImpl();
    return delay_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DC_TimingExpression createDC_TimingExpression()
  {
    DC_TimingExpressionImpl dC_TimingExpression = new DC_TimingExpressionImpl();
    return dC_TimingExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Periodic_Constraint createPeriodic_Constraint()
  {
    Periodic_ConstraintImpl periodic_Constraint = new Periodic_ConstraintImpl();
    return periodic_Constraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PC_TimingExpression createPC_TimingExpression()
  {
    PC_TimingExpressionImpl pC_TimingExpression = new PC_TimingExpressionImpl();
    return pC_TimingExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Descriptions createDescriptions()
  {
    DescriptionsImpl descriptions = new DescriptionsImpl();
    return descriptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event_Chain createEvent_Chain()
  {
    Event_ChainImpl event_Chain = new Event_ChainImpl();
    return event_Chain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event_Function_Flow_Port createEvent_Function_Flow_Port()
  {
    Event_Function_Flow_PortImpl event_Function_Flow_Port = new Event_Function_Flow_PortImpl();
    return event_Function_Flow_Port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event_Function createEvent_Function()
  {
    Event_FunctionImpl event_Function = new Event_FunctionImpl();
    return event_Function;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Unit createUnit()
  {
    UnitImpl unit = new UnitImpl();
    return unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Quantity createQuantity()
  {
    QuantityImpl quantity = new QuantityImpl();
    return quantity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EA_Numerical createEA_Numerical()
  {
    EA_NumericalImpl eA_Numerical = new EA_NumericalImpl();
    return eA_Numerical;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PkgDslPackage getPkgDslPackage()
  {
    return (PkgDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PkgDslPackage getPackage()
  {
    return PkgDslPackage.eINSTANCE;
  }

} //PkgDslFactoryImpl
