/**
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.pkgDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import webdsl.epackage.pkgdsl.pkgDsl.PkgDslPackage;
import webdsl.epackage.pkgdsl.pkgDsl.Quantity;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Quantity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getDefine <em>Define</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getUuid <em>Uuid</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getShortname <em>Shortname</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getCategory <em>Category</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getName <em>Name</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getSubstance_exp <em>Substance exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getCurrent_exp <em>Current exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getLength_exp <em>Length exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getIntensity_exp <em>Intensity exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getMass_exp <em>Mass exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getTemp_exp <em>Temp exp</em>}</li>
 *   <li>{@link webdsl.epackage.pkgdsl.pkgDsl.impl.QuantityImpl#getTime_exp <em>Time exp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QuantityImpl extends MinimalEObjectImpl.Container implements Quantity
{
  /**
   * The default value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected static final String DEFINE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefine() <em>Define</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefine()
   * @generated
   * @ordered
   */
  protected String define = DEFINE_EDEFAULT;

  /**
   * The default value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected static final String UUID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected String uuid = UUID_EDEFAULT;

  /**
   * The default value of the '{@link #getShortname() <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortname()
   * @generated
   * @ordered
   */
  protected static final String SHORTNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getShortname() <em>Shortname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortname()
   * @generated
   * @ordered
   */
  protected String shortname = SHORTNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected static final String CATEGORY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected String category = CATEGORY_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSubstance_exp() <em>Substance exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubstance_exp()
   * @generated
   * @ordered
   */
  protected static final int SUBSTANCE_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSubstance_exp() <em>Substance exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubstance_exp()
   * @generated
   * @ordered
   */
  protected int substance_exp = SUBSTANCE_EXP_EDEFAULT;

  /**
   * The default value of the '{@link #getCurrent_exp() <em>Current exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurrent_exp()
   * @generated
   * @ordered
   */
  protected static final int CURRENT_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCurrent_exp() <em>Current exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurrent_exp()
   * @generated
   * @ordered
   */
  protected int current_exp = CURRENT_EXP_EDEFAULT;

  /**
   * The default value of the '{@link #getLength_exp() <em>Length exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength_exp()
   * @generated
   * @ordered
   */
  protected static final int LENGTH_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLength_exp() <em>Length exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLength_exp()
   * @generated
   * @ordered
   */
  protected int length_exp = LENGTH_EXP_EDEFAULT;

  /**
   * The default value of the '{@link #getIntensity_exp() <em>Intensity exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntensity_exp()
   * @generated
   * @ordered
   */
  protected static final int INTENSITY_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIntensity_exp() <em>Intensity exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntensity_exp()
   * @generated
   * @ordered
   */
  protected int intensity_exp = INTENSITY_EXP_EDEFAULT;

  /**
   * The default value of the '{@link #getMass_exp() <em>Mass exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMass_exp()
   * @generated
   * @ordered
   */
  protected static final int MASS_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMass_exp() <em>Mass exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMass_exp()
   * @generated
   * @ordered
   */
  protected int mass_exp = MASS_EXP_EDEFAULT;

  /**
   * The default value of the '{@link #getTemp_exp() <em>Temp exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTemp_exp()
   * @generated
   * @ordered
   */
  protected static final int TEMP_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTemp_exp() <em>Temp exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTemp_exp()
   * @generated
   * @ordered
   */
  protected int temp_exp = TEMP_EXP_EDEFAULT;

  /**
   * The default value of the '{@link #getTime_exp() <em>Time exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime_exp()
   * @generated
   * @ordered
   */
  protected static final int TIME_EXP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTime_exp() <em>Time exp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime_exp()
   * @generated
   * @ordered
   */
  protected int time_exp = TIME_EXP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuantityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PkgDslPackage.Literals.QUANTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDefine()
  {
    return define;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefine(String newDefine)
  {
    String oldDefine = define;
    define = newDefine;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__DEFINE, oldDefine, define));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUuid()
  {
    return uuid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUuid(String newUuid)
  {
    String oldUuid = uuid;
    uuid = newUuid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__UUID, oldUuid, uuid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getShortname()
  {
    return shortname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShortname(String newShortname)
  {
    String oldShortname = shortname;
    shortname = newShortname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__SHORTNAME, oldShortname, shortname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCategory()
  {
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCategory(String newCategory)
  {
    String oldCategory = category;
    category = newCategory;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__CATEGORY, oldCategory, category));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSubstance_exp()
  {
    return substance_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubstance_exp(int newSubstance_exp)
  {
    int oldSubstance_exp = substance_exp;
    substance_exp = newSubstance_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__SUBSTANCE_EXP, oldSubstance_exp, substance_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCurrent_exp()
  {
    return current_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCurrent_exp(int newCurrent_exp)
  {
    int oldCurrent_exp = current_exp;
    current_exp = newCurrent_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__CURRENT_EXP, oldCurrent_exp, current_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLength_exp()
  {
    return length_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLength_exp(int newLength_exp)
  {
    int oldLength_exp = length_exp;
    length_exp = newLength_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__LENGTH_EXP, oldLength_exp, length_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getIntensity_exp()
  {
    return intensity_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIntensity_exp(int newIntensity_exp)
  {
    int oldIntensity_exp = intensity_exp;
    intensity_exp = newIntensity_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__INTENSITY_EXP, oldIntensity_exp, intensity_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMass_exp()
  {
    return mass_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMass_exp(int newMass_exp)
  {
    int oldMass_exp = mass_exp;
    mass_exp = newMass_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__MASS_EXP, oldMass_exp, mass_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTemp_exp()
  {
    return temp_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTemp_exp(int newTemp_exp)
  {
    int oldTemp_exp = temp_exp;
    temp_exp = newTemp_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__TEMP_EXP, oldTemp_exp, temp_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTime_exp()
  {
    return time_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTime_exp(int newTime_exp)
  {
    int oldTime_exp = time_exp;
    time_exp = newTime_exp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PkgDslPackage.QUANTITY__TIME_EXP, oldTime_exp, time_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PkgDslPackage.QUANTITY__DEFINE:
        return getDefine();
      case PkgDslPackage.QUANTITY__UUID:
        return getUuid();
      case PkgDslPackage.QUANTITY__SHORTNAME:
        return getShortname();
      case PkgDslPackage.QUANTITY__CATEGORY:
        return getCategory();
      case PkgDslPackage.QUANTITY__NAME:
        return getName();
      case PkgDslPackage.QUANTITY__SUBSTANCE_EXP:
        return getSubstance_exp();
      case PkgDslPackage.QUANTITY__CURRENT_EXP:
        return getCurrent_exp();
      case PkgDslPackage.QUANTITY__LENGTH_EXP:
        return getLength_exp();
      case PkgDslPackage.QUANTITY__INTENSITY_EXP:
        return getIntensity_exp();
      case PkgDslPackage.QUANTITY__MASS_EXP:
        return getMass_exp();
      case PkgDslPackage.QUANTITY__TEMP_EXP:
        return getTemp_exp();
      case PkgDslPackage.QUANTITY__TIME_EXP:
        return getTime_exp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PkgDslPackage.QUANTITY__DEFINE:
        setDefine((String)newValue);
        return;
      case PkgDslPackage.QUANTITY__UUID:
        setUuid((String)newValue);
        return;
      case PkgDslPackage.QUANTITY__SHORTNAME:
        setShortname((String)newValue);
        return;
      case PkgDslPackage.QUANTITY__CATEGORY:
        setCategory((String)newValue);
        return;
      case PkgDslPackage.QUANTITY__NAME:
        setName((String)newValue);
        return;
      case PkgDslPackage.QUANTITY__SUBSTANCE_EXP:
        setSubstance_exp((Integer)newValue);
        return;
      case PkgDslPackage.QUANTITY__CURRENT_EXP:
        setCurrent_exp((Integer)newValue);
        return;
      case PkgDslPackage.QUANTITY__LENGTH_EXP:
        setLength_exp((Integer)newValue);
        return;
      case PkgDslPackage.QUANTITY__INTENSITY_EXP:
        setIntensity_exp((Integer)newValue);
        return;
      case PkgDslPackage.QUANTITY__MASS_EXP:
        setMass_exp((Integer)newValue);
        return;
      case PkgDslPackage.QUANTITY__TEMP_EXP:
        setTemp_exp((Integer)newValue);
        return;
      case PkgDslPackage.QUANTITY__TIME_EXP:
        setTime_exp((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.QUANTITY__DEFINE:
        setDefine(DEFINE_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__UUID:
        setUuid(UUID_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__SHORTNAME:
        setShortname(SHORTNAME_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__CATEGORY:
        setCategory(CATEGORY_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__SUBSTANCE_EXP:
        setSubstance_exp(SUBSTANCE_EXP_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__CURRENT_EXP:
        setCurrent_exp(CURRENT_EXP_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__LENGTH_EXP:
        setLength_exp(LENGTH_EXP_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__INTENSITY_EXP:
        setIntensity_exp(INTENSITY_EXP_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__MASS_EXP:
        setMass_exp(MASS_EXP_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__TEMP_EXP:
        setTemp_exp(TEMP_EXP_EDEFAULT);
        return;
      case PkgDslPackage.QUANTITY__TIME_EXP:
        setTime_exp(TIME_EXP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PkgDslPackage.QUANTITY__DEFINE:
        return DEFINE_EDEFAULT == null ? define != null : !DEFINE_EDEFAULT.equals(define);
      case PkgDslPackage.QUANTITY__UUID:
        return UUID_EDEFAULT == null ? uuid != null : !UUID_EDEFAULT.equals(uuid);
      case PkgDslPackage.QUANTITY__SHORTNAME:
        return SHORTNAME_EDEFAULT == null ? shortname != null : !SHORTNAME_EDEFAULT.equals(shortname);
      case PkgDslPackage.QUANTITY__CATEGORY:
        return CATEGORY_EDEFAULT == null ? category != null : !CATEGORY_EDEFAULT.equals(category);
      case PkgDslPackage.QUANTITY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PkgDslPackage.QUANTITY__SUBSTANCE_EXP:
        return substance_exp != SUBSTANCE_EXP_EDEFAULT;
      case PkgDslPackage.QUANTITY__CURRENT_EXP:
        return current_exp != CURRENT_EXP_EDEFAULT;
      case PkgDslPackage.QUANTITY__LENGTH_EXP:
        return length_exp != LENGTH_EXP_EDEFAULT;
      case PkgDslPackage.QUANTITY__INTENSITY_EXP:
        return intensity_exp != INTENSITY_EXP_EDEFAULT;
      case PkgDslPackage.QUANTITY__MASS_EXP:
        return mass_exp != MASS_EXP_EDEFAULT;
      case PkgDslPackage.QUANTITY__TEMP_EXP:
        return temp_exp != TEMP_EXP_EDEFAULT;
      case PkgDslPackage.QUANTITY__TIME_EXP:
        return time_exp != TIME_EXP_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (define: ");
    result.append(define);
    result.append(", uuid: ");
    result.append(uuid);
    result.append(", shortname: ");
    result.append(shortname);
    result.append(", category: ");
    result.append(category);
    result.append(", name: ");
    result.append(name);
    result.append(", substance_exp: ");
    result.append(substance_exp);
    result.append(", current_exp: ");
    result.append(current_exp);
    result.append(", length_exp: ");
    result.append(length_exp);
    result.append(", intensity_exp: ");
    result.append(intensity_exp);
    result.append(", mass_exp: ");
    result.append(mass_exp);
    result.append(", temp_exp: ");
    result.append(temp_exp);
    result.append(", time_exp: ");
    result.append(time_exp);
    result.append(')');
    return result.toString();
  }

} //QuantityImpl
