/*
 * generated by Xtext 2.25.0
 */
package webdsl.epackage.pkgdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import webdsl.epackage.pkgdsl.ide.contentassist.antlr.internal.InternalPkgDslParser;
import webdsl.epackage.pkgdsl.services.PkgDslGrammarAccess;

public class PkgDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PkgDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PkgDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFileAccess().getGroup(), "rule__File__Group__0");
			builder.put(grammarAccess.getEA_PackageAccess().getGroup(), "rule__EA_Package__Group__0");
			builder.put(grammarAccess.getEA_PackageAccess().getGroup_0(), "rule__EA_Package__Group_0__0");
			builder.put(grammarAccess.getEA_PackageAccess().getGroup_1(), "rule__EA_Package__Group_1__0");
			builder.put(grammarAccess.getEA_PackageAccess().getGroup_2(), "rule__EA_Package__Group_2__0");
			builder.put(grammarAccess.getEA_PackageAccess().getGroup_3(), "rule__EA_Package__Group_3__0");
			builder.put(grammarAccess.getEA_PackageAccess().getGroup_4(), "rule__EA_Package__Group_4__0");
			builder.put(grammarAccess.getSub_PackageAccess().getGroup(), "rule__Sub_Package__Group__0");
			builder.put(grammarAccess.getNested_PackageAccess().getGroup(), "rule__Nested_Package__Group__0");
			builder.put(grammarAccess.getElementAccess().getGroup(), "rule__Element__Group__0");
			builder.put(grammarAccess.getElementsAccess().getGroup(), "rule__Elements__Group__0");
			builder.put(grammarAccess.getTimingAccess().getGroup(), "rule__Timing__Group__0");
			builder.put(grammarAccess.getTimingAccess().getGroup_10(), "rule__Timing__Group_10__0");
			builder.put(grammarAccess.getConstraintsAccess().getGroup(), "rule__Constraints__Group__0");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getGroup(), "rule__Reaction_Constraint__Group__0");
			builder.put(grammarAccess.getRC_TimingExpressionAccess().getGroup(), "rule__RC_TimingExpression__Group__0");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getGroup(), "rule__Pattern_Constraint__Group__0");
			builder.put(grammarAccess.getPattern_Constraint_TimingExpressionAccess().getGroup(), "rule__Pattern_Constraint_TimingExpression__Group__0");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getGroup(), "rule__Order_Constraint__Group__0");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getGroup(), "rule__Execution_Time_Constraint__Group__0");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getGroup_10(), "rule__Execution_Time_Constraint__Group_10__0");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getGroup_11(), "rule__Execution_Time_Constraint__Group_11__0");
			builder.put(grammarAccess.getETC_TimingExpressionAccess().getGroup(), "rule__ETC_TimingExpression__Group__0");
			builder.put(grammarAccess.getAge_ConstraintAccess().getGroup(), "rule__Age_Constraint__Group__0");
			builder.put(grammarAccess.getTest1Access().getGroup(), "rule__Test1__Group__0");
			builder.put(grammarAccess.getAC_TimingExpressionAccess().getGroup(), "rule__AC_TimingExpression__Group__0");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getGroup(), "rule__Delay_Constraint__Group__0");
			builder.put(grammarAccess.getDC_TimingExpressionAccess().getGroup(), "rule__DC_TimingExpression__Group__0");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getGroup(), "rule__Periodic_Constraint__Group__0");
			builder.put(grammarAccess.getPC_TimingExpressionAccess().getGroup(), "rule__PC_TimingExpression__Group__0");
			builder.put(grammarAccess.getDescriptionsAccess().getGroup(), "rule__Descriptions__Group__0");
			builder.put(grammarAccess.getEvent_ChainAccess().getGroup(), "rule__Event_Chain__Group__0");
			builder.put(grammarAccess.getEvent_ChainAccess().getGroup_10(), "rule__Event_Chain__Group_10__0");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getGroup(), "rule__Event_Function_Flow_Port__Group__0");
			builder.put(grammarAccess.getEvent_FunctionAccess().getGroup(), "rule__Event_Function__Group__0");
			builder.put(grammarAccess.getUnitAccess().getGroup(), "rule__Unit__Group__0");
			builder.put(grammarAccess.getUnitAccess().getGroup_10(), "rule__Unit__Group_10__0");
			builder.put(grammarAccess.getUnitAccess().getGroup_11(), "rule__Unit__Group_11__0");
			builder.put(grammarAccess.getUnitAccess().getGroup_12(), "rule__Unit__Group_12__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup(), "rule__Quantity__Group__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_10(), "rule__Quantity__Group_10__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_11(), "rule__Quantity__Group_11__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_12(), "rule__Quantity__Group_12__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_13(), "rule__Quantity__Group_13__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_14(), "rule__Quantity__Group_14__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_15(), "rule__Quantity__Group_15__0");
			builder.put(grammarAccess.getQuantityAccess().getGroup_16(), "rule__Quantity__Group_16__0");
			builder.put(grammarAccess.getEA_NumericalAccess().getGroup(), "rule__EA_Numerical__Group__0");
			builder.put(grammarAccess.getEA_NumericalAccess().getGroup_10(), "rule__EA_Numerical__Group_10__0");
			builder.put(grammarAccess.getEA_NumericalAccess().getGroup_11(), "rule__EA_Numerical__Group_11__0");
			builder.put(grammarAccess.getEA_NumericalAccess().getGroup_12(), "rule__EA_Numerical__Group_12__0");
			builder.put(grammarAccess.getFileAccess().getEa_packageAssignment_0(), "rule__File__Ea_packageAssignment_0");
			builder.put(grammarAccess.getFileAccess().getTimingAssignment_1(), "rule__File__TimingAssignment_1");
			builder.put(grammarAccess.getEA_PackageAccess().getDefineAssignment_0_0(), "rule__EA_Package__DefineAssignment_0_0");
			builder.put(grammarAccess.getEA_PackageAccess().getUuidAssignment_1_1(), "rule__EA_Package__UuidAssignment_1_1");
			builder.put(grammarAccess.getEA_PackageAccess().getShortnameAssignment_2_1(), "rule__EA_Package__ShortnameAssignment_2_1");
			builder.put(grammarAccess.getEA_PackageAccess().getCategoryAssignment_3_1(), "rule__EA_Package__CategoryAssignment_3_1");
			builder.put(grammarAccess.getEA_PackageAccess().getNameAssignment_4_1(), "rule__EA_Package__NameAssignment_4_1");
			builder.put(grammarAccess.getEA_PackageAccess().getSubpackagesAssignment_5(), "rule__EA_Package__SubpackagesAssignment_5");
			builder.put(grammarAccess.getEA_PackageAccess().getElementsAssignment_6(), "rule__EA_Package__ElementsAssignment_6");
			builder.put(grammarAccess.getSub_PackageAccess().getDefineAssignment_0(), "rule__Sub_Package__DefineAssignment_0");
			builder.put(grammarAccess.getSub_PackageAccess().getNested_packageAssignment_2(), "rule__Sub_Package__Nested_packageAssignment_2");
			builder.put(grammarAccess.getNested_PackageAccess().getDefineAssignment_0(), "rule__Nested_Package__DefineAssignment_0");
			builder.put(grammarAccess.getNested_PackageAccess().getUuidAssignment_3(), "rule__Nested_Package__UuidAssignment_3");
			builder.put(grammarAccess.getNested_PackageAccess().getShortnameAssignment_5(), "rule__Nested_Package__ShortnameAssignment_5");
			builder.put(grammarAccess.getNested_PackageAccess().getCategoryAssignment_7(), "rule__Nested_Package__CategoryAssignment_7");
			builder.put(grammarAccess.getNested_PackageAccess().getNameAssignment_9(), "rule__Nested_Package__NameAssignment_9");
			builder.put(grammarAccess.getNested_PackageAccess().getSubpackagesAssignment_10(), "rule__Nested_Package__SubpackagesAssignment_10");
			builder.put(grammarAccess.getNested_PackageAccess().getElementAssignment_11(), "rule__Nested_Package__ElementAssignment_11");
			builder.put(grammarAccess.getElementAccess().getDefineAssignment_0(), "rule__Element__DefineAssignment_0");
			builder.put(grammarAccess.getElementAccess().getEa_numericalAssignment_2(), "rule__Element__Ea_numericalAssignment_2");
			builder.put(grammarAccess.getElementAccess().getUnitAssignment_3(), "rule__Element__UnitAssignment_3");
			builder.put(grammarAccess.getElementAccess().getQunatityAssignment_4(), "rule__Element__QunatityAssignment_4");
			builder.put(grammarAccess.getElementAccess().getTimingAssignment_5(), "rule__Element__TimingAssignment_5");
			builder.put(grammarAccess.getElementsAccess().getDefineAssignment_0(), "rule__Elements__DefineAssignment_0");
			builder.put(grammarAccess.getElementsAccess().getEa_numericalAssignment_2(), "rule__Elements__Ea_numericalAssignment_2");
			builder.put(grammarAccess.getElementsAccess().getUnitAssignment_3(), "rule__Elements__UnitAssignment_3");
			builder.put(grammarAccess.getElementsAccess().getQunatityAssignment_4(), "rule__Elements__QunatityAssignment_4");
			builder.put(grammarAccess.getElementsAccess().getTimingAssignment_5(), "rule__Elements__TimingAssignment_5");
			builder.put(grammarAccess.getTimingAccess().getDefineAssignment_0(), "rule__Timing__DefineAssignment_0");
			builder.put(grammarAccess.getTimingAccess().getUuidAssignment_3(), "rule__Timing__UuidAssignment_3");
			builder.put(grammarAccess.getTimingAccess().getShortnameAssignment_5(), "rule__Timing__ShortnameAssignment_5");
			builder.put(grammarAccess.getTimingAccess().getCategoryAssignment_7(), "rule__Timing__CategoryAssignment_7");
			builder.put(grammarAccess.getTimingAccess().getNameAssignment_9(), "rule__Timing__NameAssignment_9");
			builder.put(grammarAccess.getTimingAccess().getTraceable_specificationAssignment_10_1(), "rule__Timing__Traceable_specificationAssignment_10_1");
			builder.put(grammarAccess.getTimingAccess().getDescriptionsAssignment_11(), "rule__Timing__DescriptionsAssignment_11");
			builder.put(grammarAccess.getTimingAccess().getConstraintsAssignment_12(), "rule__Timing__ConstraintsAssignment_12");
			builder.put(grammarAccess.getConstraintsAccess().getDefineAssignment_0(), "rule__Constraints__DefineAssignment_0");
			builder.put(grammarAccess.getConstraintsAccess().getPeriodic_constraintAssignment_2(), "rule__Constraints__Periodic_constraintAssignment_2");
			builder.put(grammarAccess.getConstraintsAccess().getDelay_constraintAssignment_3(), "rule__Constraints__Delay_constraintAssignment_3");
			builder.put(grammarAccess.getConstraintsAccess().getAge_constraintAssignment_4(), "rule__Constraints__Age_constraintAssignment_4");
			builder.put(grammarAccess.getConstraintsAccess().getExecution_time_constraintAssignment_5(), "rule__Constraints__Execution_time_constraintAssignment_5");
			builder.put(grammarAccess.getConstraintsAccess().getOrder_constraintAssignment_6(), "rule__Constraints__Order_constraintAssignment_6");
			builder.put(grammarAccess.getConstraintsAccess().getPattern_constraintAssignment_7(), "rule__Constraints__Pattern_constraintAssignment_7");
			builder.put(grammarAccess.getConstraintsAccess().getReaction_constraintAssignment_8(), "rule__Constraints__Reaction_constraintAssignment_8");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getDefineAssignment_0(), "rule__Reaction_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getUuidAssignment_3(), "rule__Reaction_Constraint__UuidAssignment_3");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getShortnameAssignment_5(), "rule__Reaction_Constraint__ShortnameAssignment_5");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getCategoryAssignment_7(), "rule__Reaction_Constraint__CategoryAssignment_7");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getNameAssignment_9(), "rule__Reaction_Constraint__NameAssignment_9");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getScopeAssignment_11(), "rule__Reaction_Constraint__ScopeAssignment_11");
			builder.put(grammarAccess.getReaction_ConstraintAccess().getTimingexpressionAssignment_12(), "rule__Reaction_Constraint__TimingexpressionAssignment_12");
			builder.put(grammarAccess.getRC_TimingExpressionAccess().getDefineAssignment_0(), "rule__RC_TimingExpression__DefineAssignment_0");
			builder.put(grammarAccess.getRC_TimingExpressionAccess().getNameAssignment_3(), "rule__RC_TimingExpression__NameAssignment_3");
			builder.put(grammarAccess.getRC_TimingExpressionAccess().getTypeAssignment_5(), "rule__RC_TimingExpression__TypeAssignment_5");
			builder.put(grammarAccess.getRC_TimingExpressionAccess().getValueAssignment_7(), "rule__RC_TimingExpression__ValueAssignment_7");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getDefineAssignment_0(), "rule__Pattern_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getUuidAssignment_3(), "rule__Pattern_Constraint__UuidAssignment_3");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getShortnameAssignment_5(), "rule__Pattern_Constraint__ShortnameAssignment_5");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getCategoryAssignment_7(), "rule__Pattern_Constraint__CategoryAssignment_7");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getNameAssignment_9(), "rule__Pattern_Constraint__NameAssignment_9");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getEventAssignment_11(), "rule__Pattern_Constraint__EventAssignment_11");
			builder.put(grammarAccess.getPattern_ConstraintAccess().getTimingexpressionAssignment_12(), "rule__Pattern_Constraint__TimingexpressionAssignment_12");
			builder.put(grammarAccess.getPattern_Constraint_TimingExpressionAccess().getDefineAssignment_0(), "rule__Pattern_Constraint_TimingExpression__DefineAssignment_0");
			builder.put(grammarAccess.getPattern_Constraint_TimingExpressionAccess().getNameAssignment_3(), "rule__Pattern_Constraint_TimingExpression__NameAssignment_3");
			builder.put(grammarAccess.getPattern_Constraint_TimingExpressionAccess().getTypeAssignment_5(), "rule__Pattern_Constraint_TimingExpression__TypeAssignment_5");
			builder.put(grammarAccess.getPattern_Constraint_TimingExpressionAccess().getValueAssignment_7(), "rule__Pattern_Constraint_TimingExpression__ValueAssignment_7");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getDefineAssignment_0(), "rule__Order_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getUuidAssignment_3(), "rule__Order_Constraint__UuidAssignment_3");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getShortnameAssignment_5(), "rule__Order_Constraint__ShortnameAssignment_5");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getCategoryAssignment_7(), "rule__Order_Constraint__CategoryAssignment_7");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getNameAssignment_9(), "rule__Order_Constraint__NameAssignment_9");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getTargetAssignment_11(), "rule__Order_Constraint__TargetAssignment_11");
			builder.put(grammarAccess.getOrder_ConstraintAccess().getSourceAssignment_13(), "rule__Order_Constraint__SourceAssignment_13");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getDefineAssignment_0(), "rule__Execution_Time_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getUuidAssignment_3(), "rule__Execution_Time_Constraint__UuidAssignment_3");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getShortnameAssignment_5(), "rule__Execution_Time_Constraint__ShortnameAssignment_5");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getCategoryAssignment_7(), "rule__Execution_Time_Constraint__CategoryAssignment_7");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getNameAssignment_9(), "rule__Execution_Time_Constraint__NameAssignment_9");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getResume_refAssignment_10_1(), "rule__Execution_Time_Constraint__Resume_refAssignment_10_1");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getPreemption_refsAssignment_11_1(), "rule__Execution_Time_Constraint__Preemption_refsAssignment_11_1");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getStartAssignment_13(), "rule__Execution_Time_Constraint__StartAssignment_13");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getStopAssignment_15(), "rule__Execution_Time_Constraint__StopAssignment_15");
			builder.put(grammarAccess.getExecution_Time_ConstraintAccess().getTimingexpressionAssignment_16(), "rule__Execution_Time_Constraint__TimingexpressionAssignment_16");
			builder.put(grammarAccess.getETC_TimingExpressionAccess().getDefineAssignment_0(), "rule__ETC_TimingExpression__DefineAssignment_0");
			builder.put(grammarAccess.getETC_TimingExpressionAccess().getNameAssignment_3(), "rule__ETC_TimingExpression__NameAssignment_3");
			builder.put(grammarAccess.getETC_TimingExpressionAccess().getTypeAssignment_5(), "rule__ETC_TimingExpression__TypeAssignment_5");
			builder.put(grammarAccess.getETC_TimingExpressionAccess().getValueAssignment_7(), "rule__ETC_TimingExpression__ValueAssignment_7");
			builder.put(grammarAccess.getAge_ConstraintAccess().getDefineAssignment_0(), "rule__Age_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getAge_ConstraintAccess().getTestAssignment_2(), "rule__Age_Constraint__TestAssignment_2");
			builder.put(grammarAccess.getTest1Access().getUuidAssignment_1(), "rule__Test1__UuidAssignment_1");
			builder.put(grammarAccess.getTest1Access().getShortnameAssignment_3(), "rule__Test1__ShortnameAssignment_3");
			builder.put(grammarAccess.getTest1Access().getCategoryAssignment_5(), "rule__Test1__CategoryAssignment_5");
			builder.put(grammarAccess.getTest1Access().getNameAssignment_7(), "rule__Test1__NameAssignment_7");
			builder.put(grammarAccess.getTest1Access().getScopeAssignment_9(), "rule__Test1__ScopeAssignment_9");
			builder.put(grammarAccess.getTest1Access().getTimingexpressionAssignment_10(), "rule__Test1__TimingexpressionAssignment_10");
			builder.put(grammarAccess.getAC_TimingExpressionAccess().getDefineAssignment_0(), "rule__AC_TimingExpression__DefineAssignment_0");
			builder.put(grammarAccess.getAC_TimingExpressionAccess().getNameAssignment_3(), "rule__AC_TimingExpression__NameAssignment_3");
			builder.put(grammarAccess.getAC_TimingExpressionAccess().getTypeAssignment_5(), "rule__AC_TimingExpression__TypeAssignment_5");
			builder.put(grammarAccess.getAC_TimingExpressionAccess().getValueAssignment_7(), "rule__AC_TimingExpression__ValueAssignment_7");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getDefineAssignment_0(), "rule__Delay_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getUuidAssignment_3(), "rule__Delay_Constraint__UuidAssignment_3");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getShortnameAssignment_5(), "rule__Delay_Constraint__ShortnameAssignment_5");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getCategoryAssignment_7(), "rule__Delay_Constraint__CategoryAssignment_7");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getNameAssignment_9(), "rule__Delay_Constraint__NameAssignment_9");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getTargetAssignment_11(), "rule__Delay_Constraint__TargetAssignment_11");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getSourceAssignment_13(), "rule__Delay_Constraint__SourceAssignment_13");
			builder.put(grammarAccess.getDelay_ConstraintAccess().getTimingexpressionAssignment_14(), "rule__Delay_Constraint__TimingexpressionAssignment_14");
			builder.put(grammarAccess.getDC_TimingExpressionAccess().getDefineAssignment_0(), "rule__DC_TimingExpression__DefineAssignment_0");
			builder.put(grammarAccess.getDC_TimingExpressionAccess().getNameAssignment_3(), "rule__DC_TimingExpression__NameAssignment_3");
			builder.put(grammarAccess.getDC_TimingExpressionAccess().getTypeAssignment_5(), "rule__DC_TimingExpression__TypeAssignment_5");
			builder.put(grammarAccess.getDC_TimingExpressionAccess().getValueAssignment_7(), "rule__DC_TimingExpression__ValueAssignment_7");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getDefineAssignment_0(), "rule__Periodic_Constraint__DefineAssignment_0");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getUuidAssignment_3(), "rule__Periodic_Constraint__UuidAssignment_3");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getShortnameAssignment_5(), "rule__Periodic_Constraint__ShortnameAssignment_5");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getCategoryAssignment_7(), "rule__Periodic_Constraint__CategoryAssignment_7");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getNameAssignment_9(), "rule__Periodic_Constraint__NameAssignment_9");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getEventAssignment_11(), "rule__Periodic_Constraint__EventAssignment_11");
			builder.put(grammarAccess.getPeriodic_ConstraintAccess().getTimingexpressionAssignment_12(), "rule__Periodic_Constraint__TimingexpressionAssignment_12");
			builder.put(grammarAccess.getPC_TimingExpressionAccess().getDefineAssignment_0(), "rule__PC_TimingExpression__DefineAssignment_0");
			builder.put(grammarAccess.getPC_TimingExpressionAccess().getNameAssignment_3(), "rule__PC_TimingExpression__NameAssignment_3");
			builder.put(grammarAccess.getPC_TimingExpressionAccess().getTypeAssignment_5(), "rule__PC_TimingExpression__TypeAssignment_5");
			builder.put(grammarAccess.getPC_TimingExpressionAccess().getValueAssignment_7(), "rule__PC_TimingExpression__ValueAssignment_7");
			builder.put(grammarAccess.getDescriptionsAccess().getDefineAssignment_0(), "rule__Descriptions__DefineAssignment_0");
			builder.put(grammarAccess.getDescriptionsAccess().getEvent_functionAssignment_2(), "rule__Descriptions__Event_functionAssignment_2");
			builder.put(grammarAccess.getDescriptionsAccess().getEvent_function_flow_portAssignment_3(), "rule__Descriptions__Event_function_flow_portAssignment_3");
			builder.put(grammarAccess.getDescriptionsAccess().getEvent_chainAssignment_4(), "rule__Descriptions__Event_chainAssignment_4");
			builder.put(grammarAccess.getEvent_ChainAccess().getDefineAssignment_0(), "rule__Event_Chain__DefineAssignment_0");
			builder.put(grammarAccess.getEvent_ChainAccess().getUuidAssignment_3(), "rule__Event_Chain__UuidAssignment_3");
			builder.put(grammarAccess.getEvent_ChainAccess().getShortnameAssignment_5(), "rule__Event_Chain__ShortnameAssignment_5");
			builder.put(grammarAccess.getEvent_ChainAccess().getCategoryAssignment_7(), "rule__Event_Chain__CategoryAssignment_7");
			builder.put(grammarAccess.getEvent_ChainAccess().getNameAssignment_9(), "rule__Event_Chain__NameAssignment_9");
			builder.put(grammarAccess.getEvent_ChainAccess().getSegment_refAssignment_10_1(), "rule__Event_Chain__Segment_refAssignment_10_1");
			builder.put(grammarAccess.getEvent_ChainAccess().getStimulusAssignment_12(), "rule__Event_Chain__StimulusAssignment_12");
			builder.put(grammarAccess.getEvent_ChainAccess().getResponseAssignment_14(), "rule__Event_Chain__ResponseAssignment_14");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getDefineAssignment_0(), "rule__Event_Function_Flow_Port__DefineAssignment_0");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getUuidAssignment_3(), "rule__Event_Function_Flow_Port__UuidAssignment_3");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getShortnameAssignment_5(), "rule__Event_Function_Flow_Port__ShortnameAssignment_5");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getCategoryAssignment_7(), "rule__Event_Function_Flow_Port__CategoryAssignment_7");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getNameAssignment_9(), "rule__Event_Function_Flow_Port__NameAssignment_9");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getFunc_typeAssignment_11(), "rule__Event_Function_Flow_Port__Func_typeAssignment_11");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getFunc_valueAssignment_13(), "rule__Event_Function_Flow_Port__Func_valueAssignment_13");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getFunc_prototypeAssignment_15(), "rule__Event_Function_Flow_Port__Func_prototypeAssignment_15");
			builder.put(grammarAccess.getEvent_Function_Flow_PortAccess().getFunc_flow_portAssignment_17(), "rule__Event_Function_Flow_Port__Func_flow_portAssignment_17");
			builder.put(grammarAccess.getEvent_FunctionAccess().getDefineAssignment_0(), "rule__Event_Function__DefineAssignment_0");
			builder.put(grammarAccess.getEvent_FunctionAccess().getUuidAssignment_3(), "rule__Event_Function__UuidAssignment_3");
			builder.put(grammarAccess.getEvent_FunctionAccess().getShortnameAssignment_5(), "rule__Event_Function__ShortnameAssignment_5");
			builder.put(grammarAccess.getEvent_FunctionAccess().getCategoryAssignment_7(), "rule__Event_Function__CategoryAssignment_7");
			builder.put(grammarAccess.getEvent_FunctionAccess().getNameAssignment_9(), "rule__Event_Function__NameAssignment_9");
			builder.put(grammarAccess.getEvent_FunctionAccess().getFunc_typeAssignment_11(), "rule__Event_Function__Func_typeAssignment_11");
			builder.put(grammarAccess.getEvent_FunctionAccess().getFunc_valueAssignment_13(), "rule__Event_Function__Func_valueAssignment_13");
			builder.put(grammarAccess.getEvent_FunctionAccess().getFunc_prototype_targetAssignment_15(), "rule__Event_Function__Func_prototype_targetAssignment_15");
			builder.put(grammarAccess.getEvent_FunctionAccess().getFunc_prototype_contextAssignment_17(), "rule__Event_Function__Func_prototype_contextAssignment_17");
			builder.put(grammarAccess.getUnitAccess().getDefineAssignment_0(), "rule__Unit__DefineAssignment_0");
			builder.put(grammarAccess.getUnitAccess().getUuidAssignment_3(), "rule__Unit__UuidAssignment_3");
			builder.put(grammarAccess.getUnitAccess().getShortnameAssignment_5(), "rule__Unit__ShortnameAssignment_5");
			builder.put(grammarAccess.getUnitAccess().getCategoryAssignment_7(), "rule__Unit__CategoryAssignment_7");
			builder.put(grammarAccess.getUnitAccess().getNameAssignment_9(), "rule__Unit__NameAssignment_9");
			builder.put(grammarAccess.getUnitAccess().getFactorAssignment_10_1(), "rule__Unit__FactorAssignment_10_1");
			builder.put(grammarAccess.getUnitAccess().getSymbolAssignment_11_1(), "rule__Unit__SymbolAssignment_11_1");
			builder.put(grammarAccess.getUnitAccess().getOffsetAssignment_12_1(), "rule__Unit__OffsetAssignment_12_1");
			builder.put(grammarAccess.getUnitAccess().getQuantityAssignment_14(), "rule__Unit__QuantityAssignment_14");
			builder.put(grammarAccess.getQuantityAccess().getDefineAssignment_0(), "rule__Quantity__DefineAssignment_0");
			builder.put(grammarAccess.getQuantityAccess().getUuidAssignment_3(), "rule__Quantity__UuidAssignment_3");
			builder.put(grammarAccess.getQuantityAccess().getShortnameAssignment_5(), "rule__Quantity__ShortnameAssignment_5");
			builder.put(grammarAccess.getQuantityAccess().getCategoryAssignment_7(), "rule__Quantity__CategoryAssignment_7");
			builder.put(grammarAccess.getQuantityAccess().getNameAssignment_9(), "rule__Quantity__NameAssignment_9");
			builder.put(grammarAccess.getQuantityAccess().getSubstance_expAssignment_10_1(), "rule__Quantity__Substance_expAssignment_10_1");
			builder.put(grammarAccess.getQuantityAccess().getCurrent_expAssignment_11_1(), "rule__Quantity__Current_expAssignment_11_1");
			builder.put(grammarAccess.getQuantityAccess().getLength_expAssignment_12_1(), "rule__Quantity__Length_expAssignment_12_1");
			builder.put(grammarAccess.getQuantityAccess().getIntensity_expAssignment_13_1(), "rule__Quantity__Intensity_expAssignment_13_1");
			builder.put(grammarAccess.getQuantityAccess().getMass_expAssignment_14_1(), "rule__Quantity__Mass_expAssignment_14_1");
			builder.put(grammarAccess.getQuantityAccess().getTemp_expAssignment_15_1(), "rule__Quantity__Temp_expAssignment_15_1");
			builder.put(grammarAccess.getQuantityAccess().getTime_expAssignment_16_1(), "rule__Quantity__Time_expAssignment_16_1");
			builder.put(grammarAccess.getEA_NumericalAccess().getDefineAssignment_0(), "rule__EA_Numerical__DefineAssignment_0");
			builder.put(grammarAccess.getEA_NumericalAccess().getUuidAssignment_3(), "rule__EA_Numerical__UuidAssignment_3");
			builder.put(grammarAccess.getEA_NumericalAccess().getShortnameAssignment_5(), "rule__EA_Numerical__ShortnameAssignment_5");
			builder.put(grammarAccess.getEA_NumericalAccess().getCategoryAssignment_7(), "rule__EA_Numerical__CategoryAssignment_7");
			builder.put(grammarAccess.getEA_NumericalAccess().getNameAssignment_9(), "rule__EA_Numerical__NameAssignment_9");
			builder.put(grammarAccess.getEA_NumericalAccess().getTextAssignment_10_1(), "rule__EA_Numerical__TextAssignment_10_1");
			builder.put(grammarAccess.getEA_NumericalAccess().getMaxAssignment_11_1(), "rule__EA_Numerical__MaxAssignment_11_1");
			builder.put(grammarAccess.getEA_NumericalAccess().getMinAssignment_12_1(), "rule__EA_Numerical__MinAssignment_12_1");
			builder.put(grammarAccess.getEA_NumericalAccess().getData_unitAssignment_14(), "rule__EA_Numerical__Data_unitAssignment_14");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PkgDslGrammarAccess grammarAccess;

	@Override
	protected InternalPkgDslParser createParser() {
		InternalPkgDslParser result = new InternalPkgDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PkgDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PkgDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
